baseURL = "https://dochne.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Dochne"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[Languages]
  [Languages.en]
  weight = 1
  LanguageName = "EN"
  LanguageDirection = "ltr"

[params]
    title = "Doug Nelson"
    author = "Doug Nelson"
    info = "Senior Software/DevOps Engineer"
    keywords = "blog,developer"
    profilePicture = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    enableMediumZoom = false
    
    disableThemeSwitcher = true
    doNotLoadAnimations = true

#     math = true
#     custom_css = ["css/custom.css"]

# Social links
[[params.socialIcons]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/dochne/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fab fa-gitlab fa-2x"
#    weight = 2
#    url = "https://gitlab.com/johndoe/"
[[params.socialIcons]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/dolondro/"

# Menu links
# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
[[menu.main]]
    name = "Kev"
    weight = 4
    url = "/kev/"
